### ISSUE TITLE
Update configuration to dogwood version

### ISSUE THREAD

**Issue by pdpinch** [mitodl/configuration#18]
Upgrade all the MITx-devops repos to work with Cypress. 

There are related issues on multiple repositories.

**Comment by bdero** [comment]
https://github.mit.edu/mitx-devops/mitx-ansible/pull/118

This can be accomplished by spinning up RP-RPC based on Carson's work and ironing out all of the rough spots.

**Comment by pdpinch** [comment]
Is this still worth doing?

The reason for the estimate of 13 is because of all the testing necessary.

**Comment by pdpinch** [comment]
related to #mitocw/179
