### ISSUE TITLE
Change mitx-fido and mitx-devops key pairs and deploy across our inventory

### ISSUE THREAD

**Issue by bdero** [mitodl/configuration#23]

**Comment by pdpinch** [comment]
Or, instead, use ODL VPN to add security groups to everything so they can only be accessed from admin instances -- fewer places that need to be updated.

**Comment by pdpinch** [comment]
@mitodl/devops is this still relevant?

**Comment by bdero** [comment]
Yes, as long as any of the old infrastructure still exists. :) Including Partners, CAS, etc.

**Comment by shaidar** [comment]
Only CAS and starcellbio left

**Comment by blarghmatey** [comment]
CAS and SCB are now on new infrastructure. Closing this ticket.
