### ISSUE TITLE
Discovery: Monitoring services

### ISSUE THREAD

**Issue by bdero** [mitodl/configuration#36]
It would be good to assess our current monitoring solution (Zenoss). Zenoss does SNMP walks and executes plugins that perform HTTP requests to healthcheck/status URLs to determine availability. It checks what services are running via patterns, etc. It does simple graphing does threshold/pattern based alerting on any data point.

However, we could really benefit from having a couple of things:

- Reactive monitoring: @blarghmatey mentioned this one. There are sometimes things we can expect to happen (on disk, for instance) the require cleanup. For example, Studio imports from git leave a buildup of repositories over time on disk. Instead of trying to build crons for all of these things that periodically check the size of the directory/rotate the oldest repositories, it would be nice to have a service that *reacts* to inode events, etc - and have these watches be controlled from a central place.

- Maintained support for our integrations: Carson made a Zenoss plugin for Hipchat, but he's gone now and it's not maintained currently, especially since he's not using Zenoss at his new job. While it's probably not going to break anytime soon, It would be nice to use a monitoring service that directly supports our chat combination.

- Not having a crappy, convoluted interface.

- An easy way to automatically add/remove managed machines upon orchestration.

**Comment by blarghmatey** [comment]
Not _totally_ critical, but definitely useful would be something that has good support for a single pane of glass approach to metrics collection as this can significantly contribute to troubleshooting. By having metrics from multiple instances and services in one location cuts down on a lot of guesswork and legwork in tracking down problems. It also simplifies the eventual process of implementing anomaly detection and adaptive alerting.
