### ISSUE TITLE
Discovery: Logging platforms

### ISSUE THREAD

**Issue by pdpinch** [mitodl/configuration#38]
reinvest in ELK or use a service?

if ELK, we need a 3-node cluster
or would we use Amazon's Elasticsearch service?

Need to consider FERPA requirements

- [X] Ask Logentries about FERPA compliance
- [ ] Ask IS&T about meaning of DLT's claim of FERPA compliance
- [ ] Ask Loggly about FERPA compliance

**Comment by pdpinch** [comment]
@blarghmatey has been in touch with Logentries, and they are happy to sell us a product that filters our logs on the way out to their service -- which defeats the purpose.

**Comment by blarghmatey** [comment]
I have contacted Loggly to ask  about FERPA compliance but have not yet received a response. The current thinking is that we will reinvest in the ELK stack.

**Comment by pdpinch** [comment]
I spoke with IS&T about DLT's claim of FERPA-compliance on AWS. It passes muster for me. I'm still trying to find out if MIT agrees, but as long as we have edX in AWS it is fine to have logging in AWS.

**Comment by pdpinch** [comment]
@blarghmatey I think we can call this done, because we've decided to move ahead with ELK?

**Comment by blarghmatey** [comment]
@pdpinch Yes, this is complete. Marking as done.
