### ISSUE TITLE
Discovery: secret management options (vault)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/configuration#42]
Consider Ansible Vault or Hashicorp vault

What about deployment?

**Comment by pdpinch** [comment]
Do either of these help with notifications of expiration dates?

**Comment by blarghmatey** [comment]
Worth looking at pinterest/knox as well

**Comment by blarghmatey** [comment]
So, after further research, discussion, and deliberation the original thought of using Hashicorp Vault has become the final decision. The combination of operational simplicity, extensibility, and the ability to generate dynamic secrets, including TLS certificates, makes it the best choice currently available for our purposes.
