### ISSUE TITLE
Discovery: service discovery

### ISSUE THREAD

**Issue by pdpinch** [mitodl/configuration#43]
Currently, we use DNS naming conventions and/or IP ranges by convention to locate servers. 

Consul from hashicorp has a way for servers to announce their services to a central key=value store. Probably a requirement for using Hashicorp Vault.

**Comment by blarghmatey** [comment]
May also be worth looking into something more lightweight such as DNS-SD

**Comment by pdpinch** [comment]
@blarghmatey @bdero what's the status of this?

**Comment by blarghmatey** [comment]
This is not yet underway. I will prioritize this for the beginning of the sprint.
