### ISSUE TITLE
Don't allow instructors to mail students from staging.mitx.mit.edu

### ISSUE THREAD

**Issue by pdpinch** [mitodl/configuration#47]
See ZenDesk [#3042](https://odl.zendesk.com/agent/tickets/3042)

@itsbenweeks is it OK to turn off all mail in the app?

**Comment by itsbenweeks** [comment]
I'm mostly for it, but if we can disable access to the mailing feature in the dashboard and allow mail to still be sent for enrollment then that may be better.

**Comment by pdpinch** [comment]
While we're at it, we should change the return address to be mitx-support@mit.edu instead of mitxmail@mit.edu

**Comment by pdpinch** [comment]
@bdero says there are settings in edx-platform for controlling when students are e-mailed invitations.

**Comment by blarghmatey** [comment]
@pdpinch is this still something that we need to address?

**Comment by pdpinch** [comment]
Since this issue was opened, edX changed the bulk mailing default to _off_ and an admin has to turn it on, on a per-course basis. 

So there's no change needed.

**Comment by itsbenweeks** [comment]
Closed by attrition.👌
