### ISSUE TITLE
Discovery: Change mongo_metadata_inheritance cache to use something other than filebased

### ISSUE THREAD

**Issue by pdpinch** [mitodl/configuration#52]
Follow-up issue to discovery in https://github.com/mitocw/edx-platform/issues/199

The filebased cache is throwing dozens of 500 errors every day, and we've confirmed that users see some (if not all) of them. 

Let's switch the cache to memcached, or possibly redis. memcached should be easier to set up (because that's what all the other caches use) but it may consume a lot of RAM (given the size of some of our courses). Redis might not be too hard to set up, if we use a service.

**Comment by pdpinch** [comment]
There is some possibility that this fix to session leakage might be relevant, but Ned ultimately thought it wasn't:

https://github.com/edx/configuration/pull/2526/files#diff-bc223d8e1006f4c717bde617c73a7a6eR148

**Comment by pdpinch** [comment]
@mitodl/devops can you let me know how the caches are configured in dogwood? (If I knew where to look in the repos, I would...)

**Comment by blarghmatey** [comment]
They are currently still file-based. I can make that change tomorrow and redeploy.

**Comment by pdpinch** [comment]
I'm curios to know if you can tell where that setting came from. I don't think it's EdX standard operating procedure. 

----------------
I am mobile.

**Comment by blarghmatey** [comment]
It was copy pasta left over from the frenzy to get things launched. We've still got a couple of items in our config settings to clean up, such as the incorrect URL setting which is resulting in the wrong redirect when attempting to view the live version of a course from studio (which I'll also be fixing in the morning).
