### ISSUE TITLE
Deployment of remote gradebook changes

### ISSUE THREAD

**Issue by pdpinch** [mitodl/configuration#59]
- [ ] edx-platform code for conditionally exporting normalized grades
- [ ] https://github.com/mitodl/PyLmod/issues/62 pylmod release 
- [ ] https://github.com/mitodl/lmod_proxy/issues/51 lmod_proxy release

This issue covers support for the release master

**Comment by bdero** [comment]
@pwilkins Would you like to take part in the releases of PyLmod and lmod_proxy? I'm thinking we can get started right after this PR is merged: https://github.com/mitodl/PyLmod/pull/61

**Comment by pwilkins** [comment]
@bdero sure.

**Comment by pdpinch** [comment]
This was done, but we had to roll it back due to an apparent bug in the code.
