### ISSUE TITLE
RP Hotfix 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/configuration#60]
- [ ] Cut branches for Cypress Hotfix 6
- [ ] Mathjax fix
- [ ] Remote gradebook enhancement
- [ ] maybe mongo_inheritence cache change

**Comment by bdero** [comment]
This is blocked by #59 , which is blocked by https://github.com/mitodl/PyLmod/pull/61

**Comment by bdero** [comment]
#54 is a subtask of this

**Comment by pdpinch** [comment]
We did this, but had to roll it back.
