### ISSUE TITLE
Tag flatfile config tasks in edxapp to speed up common deployments

### ISSUE THREAD

**Issue by bdero** [mitodl/configuration#61]
I'm thinking I'll tag the tasks as "flatfile".

**Comment by bdero** [comment]
I started testing simpler solutions here: https://github.mit.edu/mitx-devops/mitx-ansible/pull/153
But it seems there may be an Ansible behavior we have to work around.

**Comment by pdpinch** [comment]
It looks like this won't be the effort in the short term. It doesn't save as much time as we had hopedd.
