### ISSUE TITLE
response-map LTI app

### ISSUE THREAD

**Issue by pdpinch** [mitodl/configuration#63]
See [ZenDesk #3152](https://odl.zendesk.com/agent/tickets/3152)

The course EnX would like to use an LTI app so students can identify where they are on a Google Map. 

The LTI application is available from https://github.com/UQ-UQx/response-map

Discovery Questions:

- [x] Can we host it on Heroku?
- [ ] Can we host it on MIT's Heroku account (free for us)
- [x] Can the app support multiple courses, or will we need a course per app?
- [ ] Make it work under TLS

If it's helpful, I can probably track down someone from UQx who worked on this. 

via Shelly Upton:

> Some examples from Delft if you’re enrolled/can enroll
https://courses.edx.org/courses/DelftX/Frame101x/1T2015/16dee7ee1e5b498ab06b19f7f78f87a0/
https://courses.edx.org/courses/DelftX/DDA691x/3T2014/a56ac0c9e39b40cf924b526ec0fe2d17/

**Comment by blarghmatey** [comment]
So, I've got it running on Heroku but am currently unable to get it to show anything on the configured course. It seems as though it should be possible to support multiple courses but I am currently blocked on verifying that. There doesn't appear to be any reason that would prevent us from running it on the MIT Heroku account, assuming we are able to obtain the relevant credentials.

**Comment by pdpinch** [comment]
I'll take a look at the course -- where did you put it?

Also, what's the direct URL for the heroku instance?

Finally, I'm in contact with Jamie about the MIT Heroku account. He's finding out who in IS&T is the responsible party.

**Comment by blarghmatey** [comment]
I put the LTI block in the DevOps course under the LTI section. The URL is mitx-edx-lti-response-map.herokuapp.com/

**Comment by pdpinch** [comment]
DevOps course on which stack? =)

If I hit the herokuapp directly, should I expect to see anything? Maybe that's expected because it needs an LTI authentication.

**Comment by pdpinch** [comment]
I see it, at https://studio.mitx.mit.edu/container/i4x://DevOps/0.001/vertical/02935ab125c3484c9fe48e1dc1862599 <https://studio.mitx.mit.edu/container/i4x://DevOps/0.001/vertical/02935ab125c3484c9fe48e1dc1862599>

If you want to see it on staging.mitx.mit.edu <http://staging.mitx.mit.edu/> you actually need to make it live (publish the unit). 

But it doesn't seem to be working on the preview server either.

https://preview.mitx.mit.edu/courses/DevOps/0.001/2015_Summer/courseware/c8ce33eb31e3477a817baaa25f401926/d281e0ec3b94416989369e295e12495d/1

**Comment by pdpinch** [comment]
Hmm. 

So I'm getting a blank frame at https://staging.mitx.mit.edu/courses/DevOps/0.001/2015_Summer/courseware/c8ce33eb31e3477a817baaa25f401926/d281e0ec3b94416989369e295e12495d/ <https://staging.mitx.mit.edu/courses/DevOps/0.001/2015_Summer/courseware/c8ce33eb31e3477a817baaa25f401926/d281e0ec3b94416989369e295e12495d/>

But if I open the frame in a new tab, I can see the map ui. I even added a response. 

And the old test LTI appears to be working as expected. 

Not sure what's going on here. I'm might ask Shelly to take a look. 

- Peter

**Comment by blarghmatey** [comment]
Interesting. Thanks for looking.

**Comment by blarghmatey** [comment]
So, if you set it to `open in new tab: true` then it will work properly. For now, that should work but it would be good to understand why it isn't working in an iframe.

**Comment by blarghmatey** [comment]
@pdpinch Is there anything else that you would like me to do with this at the moment?

**Comment by pdpinch** [comment]
i think we're good. Let's see what Shelly finds (on ZenDesk)

**Comment by pdpinch** [comment]
Shelly noted that we're linking to an http address. Can we get an https? Perhaps that will fix the issue with rendering in a window.

**Comment by blarghmatey** [comment]
The LTI app is now working under HTTPS. After adding the SSL endpoint the OAuth signature was no longer being computed properly due to a mismatch in the protocol used in EdX and the protocol that the app was detecting due to the SSL endpoing proxying to port 80. After modifying the app to check for the `x-forwarded-proto` and `x-forwarded-port` header values it is now computing the correct signature. To use it in a course, follow the directions in the readme at mitodl/response-map.
