### ISSUE TITLE
MITx logs in kibana

### ISSUE THREAD

**Issue by pdpinch** [mitodl/configuration#67]
Now that we have a new kibana cluster for search logs, we need to work out the details of forwarding the logs from the MITx servers into it. Much of this is already done, but there appears to still be some tweaking to do. 

- [X] Add fluentd to servers to capture logs & forward to kibana
- [ ] pre-process logs so that they are indexed appropriately 
- [ ] demo new kibana interface for Peter, Ben and anyone else who needs to review MITx logs
- [x] provision more disk space for kibana indexes

**Comment by Ferdi** [comment]
Can you elaborate ?

**Comment by bdero** [comment]
I think this is getting the MITx logs forwarding into the new elasticsearch cluster.

**Comment by Ferdi** [comment]
OK, thanks. Can someone please update the description with details ?

**Comment by pdpinch** [comment]
I saw the raw data in Kibana yesterday, so it is getting forwarded. But it needs some munging to be useful. And I just heard that we ran out of disk.

**Comment by pdpinch** [comment]
We will need an estimate for the remaining work.

**Comment by pdpinch** [comment]
I updated the description

**Comment by pdpinch** [comment]
Are we hung up on this step?

> - [ ] pre-process logs so that they are indexed appropriately

**Comment by blarghmatey** [comment]
Yes, that step has not yet been completed.

**Comment by pdpinch** [comment]
What are the odds it will happen before sprint planning on Monday?

If it's not going to happen, I'll close this and open a new issue just for that bit (not sure which repo).

**Comment by pdpinch** [comment]
@blarghmatey I think we could close this. We haven't exactly done the demo but I feel like I understand enough to muddle through for now.

**Comment by blarghmatey** [comment]
I agree.
